### ISSUE TITLE
"Service Unavailable" on sendig request...

### ISSUE THREAD

**Issue by antogalli** [PaoloGi/nexi_payment#9]
Is this abandoned?
On sending request it returns: "Il servizio è momentaneamente non disponibile".
![Screenshot_1698567620](https://github.com/PaoloGi/nexi_payment/assets/3693102/5434e486-3a8a-4f7a-bb0f-e3fdc8e8ed92)

**Comment by PaoloGi** [comment]
No, i have very little time to make changes and fixes but the project is still active

For the issue: be sure to add the Alias and the Secret Key provided by nexi payment here https://ecommerce.nexi.it/area-test

**Comment by Morpheus78xxx** [comment]
Hi, sorry but still facing the problem "Il servizio è momentaneamente non disponibile"
Not sure how to retrieve the Secret Key in area-test? Can you help me, please?
